services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-20.04
    container_name: sqlserver-pdfdb
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "IronMan9021!BestHero"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: